apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alloy
  labels:
    {{- include "cloudcosts-agent.labels" . | nindent 4 }}
data:
  config.alloy: |
{{- $config := .Files.Get "config.alloy" }}
{{- $config = replace "RELEASE_NAME" .Release.Name $config }}
{{- $config = replace "RELEASE_NAMESPACE" .Release.Namespace $config }}
{{- $config = replace "GREPTIMEDB_URL" .Values.greptimedb.urlBase $config }}
{{- $config = replace "GREPTIMEDB_USERNAME" .Values.greptimedb.username $config }}
{{- $config = replace "GREPTIMEDB_PASSWORD" .Values.greptimedb.password $config }}
{{- $config = replace "CLUSTER_DATABASE" .Values.cluster.database $config }}
{{ $config | indent 4 }}
